export class ColorToken {
  private static colors = {
    light: {
      ASPHALT: '#676879',
      LIGHT_BLUE: '#61caf7',
      BASIC_BLUE: '#0073ea',
      BASIC_LIGHT_BLUE: '#c7e6fa',
      DARK_BLUE: '#0060b9',
      LINK_COLOR: '#1f76c2',
      SNOW_WHITE: '#ffffff',
      SUCCESS: '#258750',
      SUCCESS_HOVER: '#007038',
      SUCCESS_HIGHLIGHT: '#bbdbc9',
      ERROR: '#d83a52',
      ERROR_HOVER: '#b63546',
      ERROR_HIGHLIGHT: '#f4c3cb',
      PLACEHOLDER_GRAY: '#d8d8d8',
      WOLF_GRAY: '#c5c7d0',
      MUD_BLACK: '#323338',
      JACO_GRAY: '#9699a6',
      BLACK: '#000000',
      BLUE_LINKS: '#0086c0',
      BAZOOKA: '#f65f7c',
      DARK_MARBLE: '#f1f1f1',
      MARBLE: '#f7f7f7',
      GAINSBORO: '#e1e1e1',
      JEANS: '#597bfc',
      AQUA: '#00d1d1',
      HIGHLIGHT_BLUE: '#cce5ff',
      PULSE_TEXT_COLOR: '#333333',
      HIGHLIGHT: '#dff0ff',
      PLACEHOLDER_LIGHT_GRAY: '#efefef',
      SCROLLBAR_GRAY: '#b2b2b2',
      TIMELINE_GRID_BLUE: '#454662',
      TIMELINE_BLUE: '#1c1f3b',
      DEFAULT_GROUP_COLOR: '#579bfc',
      VERY_LIGHT_GRAY: '#a1a1a1',
      PULSE_BG: '#f0f0f0',
      JADE: '#03c875',
      deadline_upcoming_indication: '#5d6387',
      form_purple: '#575c96',
      form_btn_hover: '#0083d9',
      board_views_grey: '#6e6f8f',
      board_views_blue: '#1c1f3b',
      board_views_grey_hover: '#b2b3d0',
      board_views_blue_secondary: '#363a52',
      blue: '#00a9ff',
      charcoal: '#2b2c5c',
      gold: '#ffcc00',
      green: '#11dd80',
      iris: '#595ad4',
      BRAND_LIGHT_BLUE: '#00cff4',
      BRAND_MALACHITE: '#00cd6f',
      BRAND_PURPLE: '#a358d0',
      BRAND_RED: '#f74875',
      PUBLIC: '#009aff',
      PRIVATE: '#f65f7c',
      WORD_BLUE: '#2a5699',
      PPT_ORANGE: '#d64e2a',
      EXCEL_GREEN: '#207245',
      PDF_RED: '#bb0706',
      ZIP_ORANGE: '#e4901c',
      MEDIA_BLUE: '#2ea2e9',
      SURFACE: '#292f4C',
      BURNED_EGGPLANT: '#181d37',
      LIVE_BLUE: '#009aff',
      EXTRA_LIGHT_GRAY: '#edeef0',
      GLITER: '#d9f0ff',
      ULTRA_LIGHT_GRAY: '#ebebeb',
      RED_SHADOW: '#e2445c',
      GREEN_SHADOW: '#00c875',
      STORM_GRAY: '#6b6d77',
      RIVERSTONE_GRAY: '#f5f6f8',
      UI_GREY: '#e6e9ef',
      border_light_gray: '#f5f6f8',
      like_red: '#fb275d',
      LIME_GREEN: '#9cd326',
      MUSTERED: '#cab641',
      DARK_RED: '#bb3354',
      TROLLEY_GREY: '#808080',
      DARK_PURPLE: '#784bd1',
      DARK_PINK: '#ff158a',
      TURQUOISE: '#66ccff',
      LIGHT_PINK: '#ff5ac4',
      ORANGE: '#fdab3d',
      YELLOW: '#ffcb00',
      GRASS_GREEN: '#037f4c',
      AMETHYST: '#a25ddc',
      GREEN_HAZE: '#00a359',
    },
  };

  public static semantic = {
    primary_color: this.colors.light.BASIC_BLUE,
    primary_hover_color: this.colors.light.DARK_BLUE,
    primary_selected_color: this.colors.light.HIGHLIGHT_BLUE,

    positive_color: this.colors.light.SUCCESS,
    positive_color_hover: this.colors.light.SUCCESS_HOVER,
    positive_color_selected: this.colors.light.SUCCESS_HIGHLIGHT,

    negative_color: this.colors.light.ERROR,
    negative_color_hover: this.colors.light.ERROR_HOVER,
    nagative_color_selected: this.colors.light.ERROR_HIGHLIGHT,

    private_color: this.colors.light.PRIVATE,
    shareable_color: this.colors.light.DARK_PURPLE,

    inverted_color_background: this.colors.light.MUD_BLACK,
    icon_color: this.colors.light.ASPHALT,
  };

  public static background = {
    primary_background_color: this.colors.light.SNOW_WHITE,
    secondary_background_color: this.colors.light.SNOW_WHITE,
    primary_background_hover_color: this.colors.light.UI_GREY,
    inverted_color_background: this.colors.light.MUD_BLACK,
    grey_background_color: this.colors.light.RIVERSTONE_GRAY,
  };

  public static text = {
    primary_text_color: this.colors.light.MUD_BLACK,
    secondary_text_color: this.colors.light.ASPHALT,
    secondary_text_on_secondary_color: this.colors.light.ASPHALT,
    text_color_on_inverted: this.colors.light.SNOW_WHITE,
    text_color_on_primary: this.colors.light.SNOW_WHITE,
    disabled_text_color: this.colors.light.ASPHALT,
    placeholder_color: this.colors.light.ASPHALT,
    link_color: this.colors.light.LINK_COLOR,
  };

  public static border = {
    ui_border_color: this.colors.light.WOLF_GRAY,
    layout_border_color: '#d0d4e4',
  };

  public static content = {
    grass_green: '#037f4c',
    grass_green_hover: '#116846',
    grass_green_selected: '#81bfa5',
    done_green: '#00c875',
    done_green_hover: '#0f9b63',
    done_green_selected: '#80e3ba',
    bright_green: '#9cd326',
    bright_green_hover: '#7ca32b',
    bright_green_selected: '#cde992',
    saladish: '#cab641',
    saladish_hover: '#9d8f3e',
    saladish_selected: '#e4daa0',
    egg_yolk: '#ffcb00',
    egg_yolk_hover: '#c29e11',
    egg_yolk_selected: '#ffe580',
    working_orange: '#fdab3d',
    working_orange_hover: '#c0873c',
    working_orange_selected: '#fed59e',
    dark_orange: '#ff642e',
    dark_orange_hover: '#c25531',
    dark_orange_selected: '#ffb196',
    peach: '#ffadad',
    peach_hover: '#c2888a',
    peach_selected: '#ffd6d6',
    sunset: '#ff7575',
    sunset_hover: '#c26163',
    sunset_selected: '#ffbaba',
    stuck_red: '#e2445c',
    stuck_red_hover: '#ad3f51',
    stuck_red_selected: '#f0a1ad',
    dark_red: '#bb3354',
    dark_red_hover: '#92334c',
    dark_red_selected: '#dd99a9',
    sofia_pink: '#ff158a',
    sofia_pink_hover: '#c21e71',
    sofia_pink_selected: '#ff8ac4',
    lipstick: '#ff5ac4',
    lipstick_hover: '#c24e9a',
    lipstick_selected: '#fface1',
    bubble: '#faa1f1',
    bubble_hover: '#be80ba',
    bubble_selected: '#fcd0f8',
    purple: '#a25ddc',
    purple_hover: '#8050ab',
    purple_selected: '#d0aeed',
    dark_purple: '#784bd1',
    dark_purple_hover: '#6344a3',
    dark_purple_selected: '#bba5e8',
    berry: '#7e3b8a',
    berry_hover: '#673971',
    berry_selected: '#be9dc4',
    dark_indigo: '#401694',
    dark_indigo_hover: '#3c1f78',
    dark_indigo_selected: '#a08bc9',
    indigo: '#5559df',
    indigo_hover: '#4b4ead',
    indigo_selected: '#aaacef',
    navy: '#225091',
    navy_hover: '#274776',
    navy_selected: '#90a7c8',
    bright_blue: '#579bfc',
    bright_blue_hover: '#4c7cc1',
    bright_blue_selected: '#abcdfd',
    dark_blue: '#0086c0',
    dark_blue_hover: '#0f6d97',
    dark_blue_selected: '#80c2df',
    aquamarine: '#4eccc6',
    aquamarine_hover: '#469e9b',
    aquamarine_selected: '#a6e5e2',
    chili_blue: '#66ccff',
    chili_blue_hover: '#569ec3',
    chili_blue_selected: '#b2e5ff',
    river: '#68a1bd',
    river_hover: '#588095',
    river_selected: '#b3d0de',
    winter: '#9aadbd',
    winter_hover: '#7b8895',
    winter_selected: '#ccd6de',
    explosive: '#c4c4c4',
    explosive_hover: '#98999a',
    explosive_selected: '#e1e1e1',
    american_gray: '#808080',
    american_gray_hover: '#69696a',
    american_gray_selected: '#bfbfbf',
    blackish: '#333333',
    blackish_hover: '#222222',
    blackish_selected: '#999999',
    brown: '#7f5347',
    brown_hover: '#684943',
    brown_selected: '#bfa9a3',
    orchid: '#D974B0',
    orchid_hover: '#AE5D8D',
    orchid_selected: '#ECBAD7',
    tan: '#AD967A',
    tan_hover: '#8A7862',
    tan_selected: '#D6CABC',
    sky: '#A1E3F6',
    sky_hover: '#81B6C5',
    sky_selected: '#D0F1FA',
    coffee: '#BD816E',
    coffee_hover: '#976758',
    coffee_selected: '#DEC0B7',
    royal: '#2B76E5',
    royal_hover: '#225EB7',
    royal_selected: '#95BBF2',
    teal: '#175A63',
    teal_hover: '#12484F',
    teal_selected: '#8BACB1',
    lavender: '#BDA8F9',
    lavender_hover: '#9786C7',
    lavender_selected: '#DED4FC',
    steel: '#A9BEE8',
    steel_hover: '#8798BA',
    steel_selected: '#D4DFF4',
    lilac: '#9D99B9',
    lilac_hover: '#7E7A94',
    lilac_selected: '#CECCDC',
    pecan: '#563E3E',
    pecan_hover: '#453232',
    pecan_selected: '#AB9F9F',
  };

  public readonly value: string;

  constructor(value: string) {
    this.value = value;
  }
}

// --modal-background-color: var(snow_white);
// --layout-border-on-secondary-color: #d0d4e4;
// --placeholder-color-with-opacity: var(asphalt-with-opacity);
// --placeholder-on-secondary-color: var(asphalt);
// --disabled-text-on-secondary-color: #676879;
// --dark-background-color: var(riverstone_gray);
// --dark-background-on-secondary-color: var(riverstone_gray)
// --dialog-background-color: var(snow_white);
// --label-background-color: var(highlight_blue);
// --label-background-on-secondary-color: var(highlight_blue)
// --link-on-secondary-color: var(link_color);
// --box-shadow-small: 0px 4px 8px rgba(0, 0, 0, 0.2);
// --box-shadow-medium: 0px 6px 20px rgba(0, 0, 0, 0.2);
// --box-shadow-large: 0px 15px 50px rgba(0, 0, 0, 0.3);
// --box-shadow-mediun: 0px 6px 20px rgba(0, 0, 0, 0.2);
